---
abstract: 'update file access and modification times, optionally creating files if needed'
author:
  - 'Nigel Wetters Gourlay <nwetters@cpan.org>'
build_requires:
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-Touch
requires:
  Carp: '0'
  Exporter: '0'
  Fcntl: '0'
  File::stat: '0'
  IO::File: '0'
  Time::HiRes: '1.9764'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/neilb/File-Touch
  repository: https://github.com/neilb/File-Touch.git
version: '0.12'
x_generated_by_perl: v5.28.2
x_serialization_backend: 'YAML::Tiny version 1.73'
